Iter5
bonus2k/go-metrics-tpl pull request #5
Opened 2023-09-11 21:44 UTC by bonus2k

2023-09-13 13:53 UTC, kilchik requested changes

2023-09-13 13:53 UTC, kilchik commented on cmd/agent/main.go
> +func main() {
Стоит переработать структуру проекта.
В cmd должны остаться лишь main.go, именно в cmd заглядывает разработчик, который хочет начать погружаться в твой проект, с целью найти входную точку в приложение. Однако все вспомогательные пакеты располагают в /pkg (в твоем случае те сущности, которые универсальны и для агента, и для сервера) и /internal (например, пакет /internal/server/storage или /internal/storage или /internal/pkg/storage для взаимодействия с хранилищем метрик).
Для вдохновения стоит ознакомиться с проектом https://github.com/golang-standards/project-layout - в нем описаны лучшие практики структурирования реальных проектов

2023-09-13 13:53 UTC, kilchik commented on cmd/agent/main.go
> +var mapMetrics map[string]string
Глобальные переменные даже на уровне одного пакета недопустимы. Глобальные объекты чреваты
* огромными затруднениями при написании тестов
* сложноотловимыми багами, связанными с рейсами
* сложноотловимыми багами в целом, потому что к объекту есть доступ из любой функции в рамках пакета, очень сложно локализовать изменение, приведшее к багу

Объекты стоит инициализировать по принципу матрешки: есть объект server, который должен содержать объект storage - инициализируем объект storage с помощью функции storage.New() и инициализируем объект server с помощью функции server.New(storage)

2023-09-13 13:53 UTC, kilchik commented on cmd/server/controllers/handlers.go
> +	} else {
Лишние else после return

2023-09-13 13:53 UTC, kilchik commented on cmd/agent/clients/metrics_client.go
> +		req, _ := http.NewRequest(http.MethodPost, reqAddress, nil)
Не следует игнорировать ошибки, обработка ошибок обязательна в любом языке, Go же навязывает явную обработку ошибки в том месте, где она произошла

2023-09-13 13:53 UTC, kilchik commented on cmd/agent/clients/metrics_client.go
> +	client := http.DefaultClient
Нет необходимости создавать новый клиент при каждом вызове функции - его можно инициализировать один раз при конструировании структуры Connect и переиспользовать

2023-09-13 13:53 UTC, kilchik commented on cmd/agent/main.go
> +			mapMetrics = services.GetMapMetrics()
mapMetrics используется в двух независимых горутинах с доступами одновременно на чтение и на запись. 
Мапы в Go не являются потокобезопасным примитивом, тут следует воспользоваться примитивом синхронизации, например, sync.Mutex
Если вынесешь mapMetrics в отдельную структуру (условно storage), то сможешь предоставить методы на чтение и запись, в которых будет инкапсулирована защита от конкуррентного доступа

2023-09-13 13:53 UTC, kilchik commented on cmd/agent/main.go
> +			time.Sleep(time.Duration(reportInterval) * time.Second)
Здесь корректнее и идиоматичнее использовать time.Ticker вместо time.Sleep: Ticker учитывает время, потраченное на исполнение кода и вносит изменение в промежуток простаивания перед следующим вызовом. Кроме того time.Ticker позволит выполнять код для получения и отправки метрик в одной единственной горутине без потери производительности. Выглядеть это будет примерно так:
```
reportTicker := time.NewTicker(reportInterval)
pollTicker := time.NewTicker(pollInterval)
for {
  select {
    case <-reportTicker.C:
       report()
    case <-pollTicker.C:
       poll()
  }
}
```

2023-09-16 09:39 UTC, bonus2k commented on cmd/server/controllers/handlers.go
> +	} else {
но ведь num в области видимости if

2023-09-16 09:39 UTC, bonus2k commented on cmd/agent/main.go
> +func main() {
fixed

2023-09-16 09:39 UTC, bonus2k commented on cmd/agent/clients/metrics_client.go
> +		req, _ := http.NewRequest(http.MethodPost, reqAddress, nil)
fixed

2023-09-16 09:44 UTC, bonus2k commented on cmd/agent/clients/metrics_client.go
> +	client := http.DefaultClient
fixed

2023-09-16 20:44 UTC, bonus2k commented on cmd/agent/main.go
> +			time.Sleep(time.Duration(reportInterval) * time.Second)
fixed

2023-09-16 20:47 UTC, bonus2k commented on cmd/agent/main.go
> +			mapMetrics = services.GetMapMetrics()
>Кроме того time.Ticker позволит выполнять код для получения и отправки метрик в одной единственной горутине без потери производительности

Я правильгно понимаю, что используя time.Ticker в сочетаниии с select код будет исполняться в main горутине и реализация потокобезопасной работы с коллекцией отпадает?

2023-09-16 20:57 UTC, bonus2k commented on cmd/agent/main.go
> +var mapMetrics map[string]string
fixed

2023-09-18 20:05 UTC, kilchik commented on cmd/agent/main.go
> +			mapMetrics = services.GetMapMetrics()
Все верно!

2023-09-18 20:10 UTC, kilchik commented on cmd/server/controllers/handlers.go
> +	} else {
Я бы сделал 
```
num, err := ...
if err != nil {
  w.WriteHeader(http.StatusBadRequest)
  return
}
// ветка else
```
И теперь кажется, что оба return лишние, ведь дальше функция завершается.
Но тут больше вкусовщина, поэтому предлагаю оставить вариант, который тебе больше нравится

2023-09-18 20:11 UTC, kilchik approved these changes

2023-09-19 18:46 UTC, bonus2k commented on cmd/server/controllers/handlers.go
> +	} else {
Да твой вариант выглядит лучше. Спасибо!

2023-09-19 18:54 UTC, merged