Iter9
bonus2k/go-metrics-tpl pull request #9
Opened 2023-10-07 23:44 UTC by bonus2k

2023-10-12 13:31 UTC, kilchik requested changes

2023-10-12 13:31 UTC, kilchik commented on cmd/server/main.go
> +	err = multierr.Append(err, logger.Initialize(runLog))
А какой здесь профит от multierr? Разве здесь недостаточно убить сервис, если логер не смог инициализироваться?

2023-10-12 13:31 UTC, kilchik commented on internal/agent/clients/metrics_client.go
> +			logger.Log.Error("[SendToCounter]", zap.Error(err))
Ошибку предлагаю пробросить на уровень выше и там обработать, иначе не получится реализовать ни ретрай отправки, ни еще какую либо обработку

2023-10-12 13:31 UTC, kilchik commented on internal/middleware/interface/rest/compress.go
> +			return err
Важно не просто вернуть ошибку, но обрамить ее описанием того, где она произошла. Только так можно будет получить единообразный стэк ошибки и понять, какая цепочка действий к ней привела. 
Для обрамления ошибки можно воспользоваться либо пакетом `github.com/pkg/errors` и обернуть функцией `errors.Wrap(err, "create gzip writer")`, либо стандартным пакетом fmt `fmt.Errorf("create gzip wrapper: %w", err)`

2023-10-12 13:31 UTC, kilchik commented on internal/middleware/interface/rest/compress.go
> +	if r.Body != nil && isPayloadSupported(r.Header) {
Если ты инвертируешь условие, то получишь быстрый выход из функции и понизишь вложенность блока кода, который идет дальше

2023-10-12 13:31 UTC, kilchik commented on internal/server/controllers/handlers.go
> +		panic("storage not initialized")
Нельзя обрабатывать ошибки через panic. panic приведет к тому, что программа завершится, а юзер так и останется висеть в ожидании ответа. Go навязывает нам явную обработку ошибок в том месте, где она возникла. Если здесь MemStorage оказался nil, то что-то пошло не так при инициализации, а значит ты должен был завершить приложение еще при старте

2023-10-12 13:31 UTC, kilchik commented on internal/server/repositories/service.go
> +		os.Mkdir(path2.Dir(dir), 0644)
Нельзя игнорировать ошибки

2023-10-12 13:31 UTC, kilchik commented on internal/server/repositories/service.go
> +		dir, _ := path2.Split(path)
Нельзя игнорировать ошибки

2023-10-12 13:31 UTC, kilchik commented on internal/server/repositories/service.go
> +			panic(err)
Ошибку следует пробросить вверх по стеку и уже в условном main обработать. Программа не должна просто сваливаться, мы не используем паники в явном виде

2023-10-12 13:31 UTC, kilchik commented on cmd/server/flags.go
> +		storeInterval, _ = strconv.Atoi(envStoreInterval)
Нельзя игнорировать ошибки

2023-10-12 13:31 UTC, kilchik commented on cmd/server/main.go
> +		for range saveMemTicker.C {
Если storeInterval будет равен 0, то будет происходить безостановочное сохранение неизменных данных на диск. Тебе нужно реализовать по заданию синхронную запись на диск - т е при 0 только в тот момент, когда новые данные пришли на сервер, необходимо их сразу же сохранить на диск

2023-10-16 18:40 UTC, bonus2k commented on cmd/server/main.go
> +	err = multierr.Append(err, logger.Initialize(runLog))
Просто увидел его использование в какой-то из библиотек и решил попробовать, сделать код компактней. Если честно вот это if err != nil мне так глаз режут, кажется как-то не красиво)

2023-10-16 18:48 UTC, bonus2k commented on internal/agent/clients/metrics_client.go
> +			logger.Log.Error("[SendToCounter]", zap.Error(err))
fixed

2023-10-16 18:55 UTC, bonus2k commented on internal/middleware/interface/rest/compress.go
> +			return err
fixed

2023-10-16 19:01 UTC, bonus2k commented on internal/middleware/interface/rest/compress.go
> +	if r.Body != nil && isPayloadSupported(r.Header) {
fixed

2023-10-16 19:18 UTC, bonus2k commented on internal/server/controllers/handlers.go
> +		panic("storage not initialized")
Правильно ли я понимаю, что тогда MemStorage нужно проверить при его инициализации в функции init или существует вероятность, что метод init не отработаети и соотвественно проверка не будет выполнена?

2023-10-16 19:26 UTC, bonus2k commented on internal/server/repositories/service.go
> +		dir, _ := path2.Split(path)
А здесь он возвращвет не ошибку, а две стринги: путь и имя файла и игнорируется имя фала

2023-10-16 19:26 UTC, bonus2k commented on internal/server/repositories/service.go
> +		os.Mkdir(path2.Dir(dir), 0644)
fixed

2023-10-16 19:46 UTC, bonus2k commented on cmd/server/flags.go
> +		storeInterval, _ = strconv.Atoi(envStoreInterval)
fixed

2023-10-16 21:20 UTC, bonus2k commented on cmd/server/main.go
> +		for range saveMemTicker.C {
Исправил, но мне кажется решение какое то кривое... выглядит как костыль, но ничего лучше не придумал(

2023-10-17 19:49 UTC, kilchik approved these changes

2023-10-17 19:49 UTC, kilchik commented on cmd/server/flags.go
> +var storeInterval int
Напоминаю, что глобальных переменных быть не должно, они чреваты
* огромными затруднениями при написании тестов
* сложноотловимыми багами, связанными с рейсами 
* сложноотловимыми багами в целом, потому что к объекту есть доступ из любого куска кода, очень сложно локализовать изменение, приведшее к багу
Предлагаю тебе зарефакторить код перед мерджем в main

2023-10-17 19:49 UTC, kilchik commented on internal/server/repositories/service.go
> +		dir, _ := path2.Split(path)
Ага, моя ошибка

2023-10-17 19:49 UTC, kilchik commented on internal/server/repositories/service.go
> +var fileService MemStorageService
Пожалуйста, избавься от глобальных переменных, пока не поздно :))

2023-10-17 19:49 UTC, kilchik commented on internal/server/controllers/handlers.go
> +		panic("storage not initialized")
Вот мы и нащупали практическую проблемку с глобальным MemStorage.
В функции init инициализироваться ничего не должно (функцию init нельзя использовать как и глобальные переменные за очень редким исключением) , MemStorage следует конструировать как локальный объект на уровне main и прокидывать во все места, где он нужен с помощью конструкторов. Если при инициализации MemStorage возникли проблемы и по итогу он оказался == nil, то уже в этот момент нужно убить приложение с подробным логом ошибки инициализации

2023-10-18 07:34 UTC, bonus2k commented on cmd/server/flags.go
> +var storeInterval int
Принял) Исправлю

2023-11-01 19:50 UTC, merged